version: "3.9"

services:

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.${BASE_DOMAIN:-ozeliurs.com}
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_DATABASE=bookstackapp
    env_file:
      - .bookstack.env
    volumes:
      - ./bookstack_app_data:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.${BASE_DOMAIN:-ozeliurs.com}`)"
      - "traefik.http.routers.bookstack.entrypoints=websecure"
      - "traefik.http.routers.bookstack.tls=true"
      - "traefik.http.routers.bookstack.tls.certresolver=cloudflare"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
    env_file:
      - .bookstack.env
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true